workflows:
  testHola:
    name: Hola Mundo y LS
    scripts:
      - name: Imprimir Hola Mundo
        script: |
          echo "Hola Mundo"
      - name: Ejecutar ls -l
        script: |
          ls -l
