workflows:
  katalon-tests:
    name: Katalon Tests
    triggering:
      events:
        - push
    environment:
      vars:
        KATALON_VERSION: "8.0.5"
    scripts:
      - name: Install Katalon Studio
        script: |
          wget -q https://github.com/katalon-studio/katalon-studio/releases/download/v${KATALON_VERSION}/Katalon_Studio_Linux_64-${KATALON_VERSION}.tar.gz
          tar -xzf Katalon_Studio_Linux_64-${KATALON_VERSION}.tar.gz
          rm Katalon_Studio_Linux_64-${KATALON_VERSION}.tar.gz
          
      - name: Start Emulator
        script: |
          emulator @Pixel_2_API_29 &
          adb wait-for-device
          
      - name: Run Katalon Tests
        script: |
          ./Katalon_Studio_Linux_64-${KATALON_VERSION}/katalon -noSplash \
            -runMode=console \
            -projectPath="$(pwd)" \
            -retry=0 \
            -testSuitePath="Test Suites/TS_RegressionTest" \
            -browserType="Android" \
            -deviceId="emulator-5554" \
            -app="$(pwd)/General-Store.apk"
    artifacts:
      - reports/**
