workflows:
  katalon-tests:
    name: Katalon Tests
    environment:
      vars:
        KATALON_VERSION: "8.6.0"
    scripts:
      - name: Install Katalon Runtime Engine
        script: |
          curl -O https://github.com/katalon-studio/katalon-studio/releases/download/v$KATALON_VERSION/Katalon_Studio_Engine_MacOS_$KATALON_VERSION.zip
          unzip Katalon_Studio_Engine_MacOS_$KATALON_VERSION.zip -d katalon-studio
      - name: Execute Katalon Tests
        script: |
          ./katalon-studio/katalonc -testSuitePath="Test Suites/Prueba" -executionProfile="default" --config -webui.autoUpdateDrivers=true -orgId="1261789" -apiKey="0a5120e1-528e-4af3-84d4-99aaf18f2904" -testOpsProjectId="1231097" -projectPath="$FCI_PROJECT_DIR" -reportFolder="$FCI_PROJECT_DIR/report/$(date +'%Y%m%d_%H%M%S')" -report -browserType="Chrome"
